export const PATHS = {
  showcase: "/",
  discounts: "/discounts",
  products: "products",
  admin: "/admin/",
  settings: "settings",
  orders: "orders",
  wishlist: "/wishlist",
  cart: "/cart",
  success: "success",
  auth: "/auth",
  codeVerification: "/code-verification",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/profile",
};
